using Toybox.Lang;
using Toybox.Math;

// Bundled offline stations (generated by tools/build_stations.py into resources/stations):
// every subway station within 10 km of home with its lines, platform direction labels,
// entrances and the lines that ride home without a change. No schedules. Only the small
// coordinate index and one 16-station chunk are loaded at a time (glance-safe).
(:glance)
module OfflineStations {
    const E5 = 100000.0d;

    // [[station index, meters to the station point], ...] for the n nearest, nearest first.
    function nearest(lat, lon, n) {
        var out = [] as Lang.Array;
        if (!Config.coordinates(lat, lon) || n < 1) { return out; }
        var idx = StationData.index() as Lang.Array;
        var k = Math.cos(lat * Math.PI / 180);
        for (var i = 0; i + 1 < idx.size(); i += 2) {
            var dy = ((idx[i] as Lang.Number) / E5 - lat) * 111320.0;
            var dx = ((idx[i + 1] as Lang.Number) / E5 - lon) * 111320.0 * k;
            var m = Math.sqrt(dx * dx + dy * dy);
            var pos = out.size();
            while (pos > 0 && (out[pos - 1] as Lang.Array)[1] > m) { pos -= 1; }
            if (pos >= n) { continue; }
            if (out.size() < n) { out.add(null); }
            for (var j = out.size() - 1; j > pos; j -= 1) { out[j] = out[j - 1]; }
            out[pos] = [i / 2, m];
        }
        return out;
    }

    // A board-style station dictionary ("id", "name", "lat", "lon", "routes", "entrances")
    // plus "groups" (flat: routes, north label, south label, home routes north, home routes
    // south, ...) and "home" (a station near home), or null.
    function station(i) {
        if (!(i instanceof Lang.Number) || i < 0 || i >= StationData.COUNT) { return null; }
        var chunk = StationData.chunk(i / StationData.CHUNK) as Lang.Array;
        var rec = chunk[i % StationData.CHUNK] as Lang.Array;
        var lat = rec[2] as Lang.Number;
        var lon = rec[3] as Lang.Number;
        var groups = rec[4] as Lang.Array;
        var routes = [] as Lang.Array;
        for (var g = 0; g + 4 < groups.size(); g += 5) {
            var words = MtaFormat.words(groups[g]);
            for (var w = 0; w < words.size(); w += 1) {
                var seen = false;
                for (var r = 0; r < routes.size(); r += 1) { if (routes[r].equals(words[w])) { seen = true; } }
                if (!seen) { routes.add(words[w]); }
            }
        }
        var flat = rec[5] as Lang.Array;
        var entrances = [] as Lang.Array;
        for (var e = 0; e + 1 < flat.size(); e += 2) {
            entrances.add({"lat" => (lat + (flat[e] as Lang.Number)) / E5, "lon" => (lon + (flat[e + 1] as Lang.Number)) / E5});
        }
        return {"id" => rec[0], "name" => rec[1], "lat" => lat / E5, "lon" => lon / E5, "routes" => routes,
            "entrances" => entrances, "groups" => groups, "home" => rec[6] == 1, "offline" => i};
    }

    // Straight-line meters to the nearest entrance (else the station point).
    function meters(station, lat, lon) {
        var best = PackStore.meters(lat, lon, station["lat"], station["lon"]);
        var points = station["entrances"] as Lang.Array;
        for (var i = 0; i < points.size(); i += 1) {
            var m = PackStore.meters(lat, lon, points[i]["lat"], points[i]["lon"]);
            if (i == 0 || m < best) { best = m; }
        }
        return best;
    }

    // "Home: 4 5 6 Downtown, L Manhattan", "Home station", or null without a one-seat ride.
    // At most `parts` line/direction pairs (null: all).
    function hint(station, parts) {
        if (!(station instanceof Lang.Dictionary) || !(station["groups"] instanceof Lang.Array)) { return null; }
        if (station["home"] == true) { return "Home station"; }
        var g = station["groups"] as Lang.Array;
        var text = "";
        var count = 0;
        for (var i = 0; i + 4 < g.size(); i += 5) {
            for (var d = 0; d < 2; d += 1) {
                var routes = g[i + 3 + d] as Lang.String;
                if (routes.length() == 0 || (parts != null && count >= parts)) { continue; }
                count += 1;
                var label = g[i + 1 + d] as Lang.String;
                if (label.length() == 0) { label = d == 0 ? "Northbound" : "Southbound"; }
                text += (text.length() > 0 ? ", " : "") + routes + " " + label;
            }
        }
        return text.length() > 0 ? "Home: " + text : null;
    }

    // The first line that rides home (for a single bullet), else the station's first line.
    function homeRoute(station) {
        var g = station["groups"] as Lang.Array;
        for (var i = 0; station["home"] != true && i + 4 < g.size(); i += 5) {
            for (var d = 3; d < 5; d += 1) {
                var w = MtaFormat.words(g[i + d]);
                if (w.size() > 0) { return w[0]; }
            }
        }
        var routes = station["routes"] as Lang.Array;
        return routes.size() > 0 ? routes[0] : null;
    }
}
