// Generated by tools/build_stations.py; do not edit.
using Toybox.Application;

(:glance)
module StationData {
    const COUNT = 229;
    const CHUNK = 16;
    const SOURCE = "MTA 2026-09-29, GTFS 2026-10";

    function chunk(k) {
        return Application.loadResource([Rez.JsonData.StationChunk00, Rez.JsonData.StationChunk01, Rez.JsonData.StationChunk02, Rez.JsonData.StationChunk03, Rez.JsonData.StationChunk04, Rez.JsonData.StationChunk05, Rez.JsonData.StationChunk06, Rez.JsonData.StationChunk07, Rez.JsonData.StationChunk08, Rez.JsonData.StationChunk09, Rez.JsonData.StationChunk10, Rez.JsonData.StationChunk11, Rez.JsonData.StationChunk12, Rez.JsonData.StationChunk13, Rez.JsonData.StationChunk14][k]);
    }

    function index() { return Application.loadResource(Rez.JsonData.StationIndex); }
}
